### ISSUE TITLE
phosphor-settingsd is not forward compatible when new property added to interface

### ISSUE THREAD

**Issue by geissonator** [openbmc/phosphor-settingsd#16]
Ran into an interesting one recently and I'm not sure what to do about it.

https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/50231 added a new property to the xyz.openbmc_project.Control.Power.RestorePolicy interface. The issue is that if you move your firmware level from one that did not have this new property added, to one that does have it added, you lose whatever persistent value you had originally for the PowerRestorePolicy property.

phosphor-settingsd (or cereal) just silently deletes the file from /var/lib/phosphor-settings-manager/settings/xyz/openbmc_project/control/host0 with no warning or error which makes it more confusing to debug.

The old file looks like this (where value0 is the PowerRestorePolicy property value:
```
{
    "value0": {
        "cereal_class_version": 1,
        "value0": 2        
    }              
} 
```

With the latest firmware, we get this:
```
{
    "value0": {
        "cereal_class_version": 1,
        "value0": 30000000,
        "value1": 2
    }
}
```

So "value0" is now the new PowerRestoreDelay property, and "value1" is PowerRestorePolicy.

I get the complexity of trying to preserve something like this in generic code like we have in phosphor-settingsd. I'm wondering if we just get to live with this type of behavior or if there's something we could do? For our downstream firmware releases this type of behavior is not going to fly so I'll have to revert the commit that added the new PowerRestoreDelay property and any new code that references it.

I'm concerned we're going to have to review all PDI changes that added properties to existing d-bus interfaces.

**Comment by williamspatrick** [comment]
Does it have literally “value0” and “value1”?  That seems like something straightforward to fix.

**Comment by geissonator** [comment]
Per some discord discussion, it doesn't look like there's a solution for already-released firmware for this issue so in those situations, changes that add/remove properties to existing interfaces will have to be reverted (in downstream code) or custom code will need to be written to handle the upgrades gracefully.

Going forward, (this bug), we need to investigate if using name-value pars in cereal will allow it to gracefully handle this scenario.

**Comment by spinler** [comment]
Cereal does allow named values - see 'Naming values' at http://uscilab.github.io/cereal/quickstart.html.

Also, since settings does use cereal versioning (http://uscilab.github.io/cereal/serialization_functions.html#versioning -  This was implemented due to https://github.com/openbmc/openbmc/issues/2320 which did mention this problem but didn't completely solve it), it seems like we could handle this by doing something like:

1. Change the code to write with name value pairs (NVPs), and bump the version to 2.
2. On the restore check the version, and if it's 1 then read in as it currently is, and if 2+ do it using NVPs (whatever that entails).

**Comment by spinler** [comment]
I can take a shot at doing what I mentioned above.

**Comment by williamspatrick** [comment]
> On the restore check the version, and if it's 1 then read in as it currently is, and if 2+ do it using NVPs (whatever that entails).

The PDI bindings already have a "load this object from a map<string, variant>" constructor.  I'd be very surprised if this didn't work well for the Cereal v2 case.  That is what phosphor-inventory-manager uses.

**Comment by spinler** [comment]
If we wanted, we could migrate all of the files to version 2 on startup to eliminate the 'adding a property' issue from then on.

But if we did that, there would be no compatibility with previous firmware levels that didn't do this, as it takes code changes in the load() function to understand the new format.

So just skip doing that?  Or add it with a compile option for people that don't (or do) backlevel?

**Comment by williamspatrick** [comment]
We don’t have an official policy on backwards/forward compatibility. Generally we’ve only worried about moving old data forward and not maintaining compatibility with older images.

**Comment by spinler** [comment]
I guess even if the code didn't do a mass migration of the files, the original code still wouldn't understand any new NVP values written out by the new code and would probably silently reset them to their defaults.

**Comment by spinler** [comment]
It turns out that the original code can read the NVP files, so there is no issue with backwards compatibility.

Fixes up starting here: https://gerrit.openbmc.org/c/openbmc/phosphor-settingsd/+/63713
